INSERT INTO KPI.KPI_TYPES (DE_KPI_NAME, IN_ENABLED)
VALUES
('DAYS_SINCE_LAST_EXPOSURE', FALSE),
('MATCHED_KEY_COUNT', FALSE),
('MAXIMUM_RISK_SCORE', FALSE),
('ATTENUATION_DURATIONS_1', FALSE),
('ATTENUATION_DURATIONS_2', FALSE),
('ATTENUATION_DURATIONS_3', FALSE),
('SUMMATION_RISK_SCORE', FALSE),
('MATCH_CONFIRMED', TRUE),
('BLUETOOTH_ACTIVATED', TRUE)
;
