CREATE SCHEMA KPI;

CREATE SEQUENCE KPI.SQ_NM_ID_KPI_TYPE;
CREATE SEQUENCE KPI.SQ_NM_ID_KPI;
CREATE SEQUENCE KPI.SQ_NM_ID_STATISTICS_RADAR;
CREATE SEQUENCE KPI.SQ_NM_ID_STATISTICS_RADAR_CCAA;

CREATE TABLE KPI.KPI_TYPES (
    NM_ID_KPI_TYPE  BIGINT DEFAULT nextval('KPI.SQ_NM_ID_KPI_TYPE'),
    DE_KPI_NAME     CHAR VARYING(100),
    IN_ENABLED      BOOLEAN DEFAULT FALSE,
    CONSTRAINT PK_KPI_TYPE
        PRIMARY KEY (NM_ID_KPI_TYPE)
);

CREATE TABLE KPI.KPIS (
    NM_ID_KPI           INTEGER DEFAULT nextval('KPI.SQ_NM_ID_KPI'),
    NM_ID_KPI_TYPE      INTEGER,
    FC_CREATION_DATE    TIMESTAMP DEFAULT current_timestamp,
    NM_VALUE            INTEGER,
    NM_SO_TYPE          INTEGER,
    CONSTRAINT PK_KPI
        PRIMARY KEY (NM_ID_KPI),
    CONSTRAINT FK_KPI_TYPE
        FOREIGN KEY (NM_ID_KPI_TYPE)
            REFERENCES KPI.KPI_TYPES (NM_ID_KPI_TYPE)
);

CREATE TABLE KPI.CCAA (
    DE_CCAA_ID         CHAR (5),
    DE_CCAA_NUM_ID     CHAR (2),
    DE_CCAA_NAME       CHAR VARYING(100),
    FC_START_DATE      TIMESTAMP NOT NULL,
    CONSTRAINT PK_CCAA
        PRIMARY KEY (DE_CCAA_ID)
);

CREATE TABLE KPI.STATISTICS_RADAR (
    NM_ID_STATISTICS                            INTEGER DEFAULT nextval('KPI.SQ_NM_ID_STATISTICS_RADAR'),
    FC_STATISTICS_DATE                          TIMESTAMP NOT NULL,
    NM_DOWNLOADS_ANDROID                        INTEGER,
    NM_DOWNLOADS_IOS                            INTEGER,
    NM_DELIVERED_CODES_POSITIVE_CONFIRMED       INTEGER,
    NM_POSITIVES_RADAR                          INTEGER,
    CONSTRAINT PK_STATISTICS_RADAR
        PRIMARY KEY (NM_ID_STATISTICS),
    UNIQUE (FC_STATISTICS_DATE)
);

CREATE TABLE KPI.STATISTICS_RADAR_CCAA (
    NM_ID_STATISTICS                            INTEGER DEFAULT nextval('KPI.SQ_NM_ID_STATISTICS_RADAR_CCAA'),
    FC_STATISTICS_DATE                          TIMESTAMP NOT NULL,
    DE_CCAA_ID                                  CHAR (5) NOT NULL,
    NM_POSITIVES_CONFIRMED                      INTEGER,
    NM_DELIVERED_CODES_POSITIVE_CONFIRMED       INTEGER DEFAULT 0,
    NM_POSITIVES_RADAR                          INTEGER DEFAULT 0,
    CONSTRAINT PK_STATISTICS_RADAR_CCAA
        PRIMARY KEY (NM_ID_STATISTICS),
    CONSTRAINT FK_STATISTICS_RADAR_CCAA_DE_CCAA_ID
        FOREIGN KEY (DE_CCAA_ID)
            REFERENCES KPI.CCAA (DE_CCAA_ID),
    UNIQUE (FC_STATISTICS_DATE, DE_CCAA_ID)
);

CREATE TABLE KPI.SHEDLOCK (
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT PK_SHEDLOCK
        PRIMARY KEY (name)
);

ALTER SEQUENCE KPI.SQ_NM_ID_KPI_TYPE
    OWNED BY KPI.KPI_TYPES.NM_ID_KPI_TYPE;

ALTER SEQUENCE KPI.SQ_NM_ID_KPI
    OWNED BY KPI.KPIS.NM_ID_KPI;

ALTER SEQUENCE KPI.SQ_NM_ID_STATISTICS_RADAR
    OWNED BY KPI.STATISTICS_RADAR.NM_ID_STATISTICS;

ALTER SEQUENCE KPI.SQ_NM_ID_STATISTICS_RADAR_CCAA
    OWNED BY KPI.STATISTICS_RADAR_CCAA.NM_ID_STATISTICS;
    
CREATE OR REPLACE VIEW KPI.VIEW_DATA_MONTH_STATISTICS AS
SELECT YEAR, MONTH, YEAR_MONTH,
	   DOWNLOADS_ANDROID, SUM(DOWNLOADS_ANDROID) OVER (ORDER BY YEAR_MONTH) AS DOWNLOADS_ANDROID_ACC,
       DOWNLOADS_IOS, SUM(DOWNLOADS_IOS) OVER (ORDER BY YEAR_MONTH) AS DOWNLOADS_IOS_ACC,
       DELIVERED_CODES_POSITIVE_CONFIRMED, SUM(DELIVERED_CODES_POSITIVE_CONFIRMED) OVER (ORDER BY YEAR_MONTH) AS DELIVERED_CODES_POSITIVE_CONFIRMED_ACC,
	   POSITIVES_RADAR, SUM(POSITIVES_RADAR) OVER (ORDER BY YEAR_MONTH) AS POSITIVES_RADAR_ACC
FROM (
	SELECT DATE_PART('YEAR', FC_STATISTICS_DATE::DATE) AS YEAR,
		   LPAD(DATE_PART('MONTH', FC_STATISTICS_DATE::DATE)::TEXT, 2, '0') AS MONTH,
		   CONCAT(DATE_PART('YEAR', FC_STATISTICS_DATE::DATE), LPAD(DATE_PART('MONTH', FC_STATISTICS_DATE::DATE)::TEXT, 2, '0'))::INT AS YEAR_MONTH,
		   SUM(NM_DOWNLOADS_ANDROID) AS DOWNLOADS_ANDROID,
		   COUNT(*) - COUNT(NM_DOWNLOADS_ANDROID) AS CHECK_ANDROID,
		   SUM(NM_DOWNLOADS_IOS) AS DOWNLOADS_IOS,
		   COUNT(*) - COUNT(NM_DOWNLOADS_IOS) AS CHECK_IOS,	
		   SUM(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS DELIVERED_CODES_POSITIVE_CONFIRMED, 
		   COUNT(*) - COUNT(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED,
		   SUM(NM_POSITIVES_RADAR) AS POSITIVES_RADAR,
	       COUNT(*) - COUNT(NM_POSITIVES_RADAR) AS CHECK_POSITIVES_RADAR
	FROM KPI.STATISTICS_RADAR
	GROUP BY YEAR, MONTH
	ORDER BY YEAR, MONTH ) T
WHERE T.YEAR_MONTH < CONCAT(DATE_PART('YEAR', NOW())::TEXT, LPAD(DATE_PART('MONTH', NOW())::TEXT, 2, '0'))::INT
  AND T.CHECK_ANDROID = 0 
  AND T.CHECK_IOS = 0
  AND T.CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED = 0
  AND T.CHECK_POSITIVES_RADAR = 0
ORDER BY YEAR_MONTH;


CREATE OR REPLACE VIEW KPI.VIEW_DATA_WEEK_STATISTICS AS
SELECT YEAR, WEEK, YEAR_WEEK,
	   DOWNLOADS_ANDROID, SUM(DOWNLOADS_ANDROID) OVER (ORDER BY YEAR_WEEK) AS DOWNLOADS_ANDROID_ACC,
       DOWNLOADS_IOS, SUM(DOWNLOADS_IOS) OVER (ORDER BY YEAR_WEEK) AS DOWNLOADS_IOS_ACC,
       DELIVERED_CODES_POSITIVE_CONFIRMED, SUM(DELIVERED_CODES_POSITIVE_CONFIRMED) OVER (ORDER BY YEAR_WEEK) AS DELIVERED_CODES_POSITIVE_CONFIRMED_ACC,
	   POSITIVES_RADAR, SUM(POSITIVES_RADAR) OVER (ORDER BY YEAR_WEEK) AS POSITIVES_RADAR_ACC
FROM (
	SELECT DATE_PART('YEAR', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE)) AS YEAR,
		   LPAD(DATE_PART('WEEK', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE))::TEXT, 2, '0') AS WEEK,
		   CONCAT(DATE_PART('YEAR', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE)), LPAD(DATE_PART('WEEK', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE))::TEXT, 2, '0'))::INT AS YEAR_WEEK,
		   SUM(NM_DOWNLOADS_ANDROID) AS DOWNLOADS_ANDROID,
		   COUNT(*) - COUNT(NM_DOWNLOADS_ANDROID) AS CHECK_ANDROID,
		   SUM(NM_DOWNLOADS_IOS) AS DOWNLOADS_IOS,
		   COUNT(*) - COUNT(NM_DOWNLOADS_IOS) AS CHECK_IOS,	
		   SUM(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS DELIVERED_CODES_POSITIVE_CONFIRMED, 
		   COUNT(*) - COUNT(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED,
		   SUM(NM_POSITIVES_RADAR) AS POSITIVES_RADAR,
	       COUNT(*) - COUNT(NM_POSITIVES_RADAR) AS CHECK_POSITIVES_RADAR
	FROM KPI.STATISTICS_RADAR
	GROUP BY YEAR, WEEK
	ORDER BY YEAR, WEEK ) T
WHERE YEAR_WEEK < CONCAT(DATE_PART('YEAR', DATE_TRUNC('WEEK', NOW()))::TEXT, LPAD(DATE_PART('WEEK', DATE_TRUNC('WEEK', NOW()))::TEXT, 2, '0'))::INT
  AND T.CHECK_ANDROID = 0 
  AND T.CHECK_IOS = 0
  AND T.CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED = 0
  AND T.CHECK_POSITIVES_RADAR = 0
ORDER BY YEAR_WEEK;  


CREATE OR REPLACE VIEW KPI.VIEW_DATA_CCAA_MONTH_STATISTICS AS
SELECT YEAR, MONTH, YEAR_MONTH,
	   CCAA_ID, CCAA_NAME, CONFIRMED_POSITIVES,
     SUM(CONFIRMED_POSITIVES) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_MONTH) AS CONFIRMED_POSITIVES_ACC,
     DELIVERED_CODES_POSITIVE_CONFIRMED, 
	   SUM(DELIVERED_CODES_POSITIVE_CONFIRMED) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_MONTH) AS DELIVERED_CODES_POSITIVE_CONFIRMED_ACC,
	   CASE WHEN CONFIRMED_POSITIVES = 0 THEN 0.00 ELSE ((DELIVERED_CODES_POSITIVE_CONFIRMED * 100.0) / CONFIRMED_POSITIVES) END AS DELIVERED_CODES_POSITIVE_CONFIRMED_RATIO,
	   CASE WHEN (SUM(CONFIRMED_POSITIVES) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_MONTH)) = 0 THEN 0.00 ELSE (((SUM(DELIVERED_CODES_POSITIVE_CONFIRMED) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_MONTH)) * 100.0) / (SUM(CONFIRMED_POSITIVES) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_MONTH))) END AS DELIVERED_CODES_POSITIVE_CONFIRMED_ACC_RATIO,
	   POSITIVES_RADAR, SUM(POSITIVES_RADAR) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_MONTH) AS POSITIVES_RADAR_ACC,
	   CASE WHEN CONFIRMED_POSITIVES = 0 THEN 0.00 ELSE ((POSITIVES_RADAR * 100.0) / CONFIRMED_POSITIVES) END AS POSITIVES_RADAR_RATIO,
	   CASE WHEN (SUM(CONFIRMED_POSITIVES) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_MONTH)) = 0 THEN 0.00 ELSE ((SUM(POSITIVES_RADAR) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_MONTH)) * 100.0/ (SUM(CONFIRMED_POSITIVES) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_MONTH))) END AS POSITIVES_RADAR_ACC_RATIO
FROM (
SELECT DATE_PART('YEAR', FC_STATISTICS_DATE::DATE) AS YEAR,
	   LPAD(DATE_PART('MONTH', FC_STATISTICS_DATE::DATE)::TEXT, 2, '0') AS MONTH,
	   CONCAT(DATE_PART('YEAR', FC_STATISTICS_DATE::DATE), LPAD(DATE_PART('MONTH', FC_STATISTICS_DATE::DATE)::TEXT, 2, '0'))::INT AS YEAR_MONTH,
	   C.DE_CCAA_ID AS CCAA_ID,
	   C.DE_CCAA_NAME AS CCAA_NAME,
	   SUM(NM_POSITIVES_CONFIRMED) AS CONFIRMED_POSITIVES,
	   COUNT(*) - COUNT(NM_POSITIVES_CONFIRMED) AS CHECK_POSITIVES_CONFIRMED,
	   SUM(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS DELIVERED_CODES_POSITIVE_CONFIRMED,
	   COUNT(*) - COUNT(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED,
	   SUM(NM_POSITIVES_RADAR) AS POSITIVES_RADAR,
	   COUNT(*) - COUNT(NM_POSITIVES_RADAR) AS CHECK_POSITIVES_RADAR
FROM KPI.STATISTICS_RADAR_CCAA S
INNER JOIN KPI.CCAA C ON S.DE_CCAA_ID = C.DE_CCAA_ID
WHERE S.FC_STATISTICS_DATE >= C.FC_START_DATE
GROUP BY YEAR, MONTH, CCAA_ID
ORDER BY YEAR, MONTH, CCAA_ID ) T
WHERE T.YEAR_MONTH < CONCAT(DATE_PART('YEAR', NOW())::TEXT, LPAD(DATE_PART('MONTH', NOW())::TEXT, 2, '0'))::INT
  AND T.CHECK_POSITIVES_CONFIRMED = 0 
  AND T.CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED = 0
  AND T.CHECK_POSITIVES_RADAR = 0
ORDER BY YEAR_MONTH, CCAA_ID;


CREATE OR REPLACE VIEW KPI.VIEW_DATA_CCAA_WEEK_STATISTICS AS
SELECT YEAR, WEEK, YEAR_WEEK, 
 	   CCAA_ID, CCAA_NAME, CONFIRMED_POSITIVES,
     SUM(CONFIRMED_POSITIVES) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_WEEK) AS CONFIRMED_POSITIVES_ACC,
     DELIVERED_CODES_POSITIVE_CONFIRMED, 
	   SUM(DELIVERED_CODES_POSITIVE_CONFIRMED) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_WEEK) AS DELIVERED_CODES_POSITIVE_CONFIRMED_ACC,
	   CASE WHEN CONFIRMED_POSITIVES = 0 THEN 0.00 ELSE ((DELIVERED_CODES_POSITIVE_CONFIRMED * 100.0) / CONFIRMED_POSITIVES) END AS DELIVERED_CODES_POSITIVE_CONFIRMED_RATIO,
	   CASE WHEN (SUM(CONFIRMED_POSITIVES) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_WEEK)) = 0 THEN 0.00 ELSE (((SUM(DELIVERED_CODES_POSITIVE_CONFIRMED) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_WEEK)) * 100.0) / (SUM(CONFIRMED_POSITIVES) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_WEEK))) END AS DELIVERED_CODES_POSITIVE_CONFIRMED_ACC_RATIO,
	   POSITIVES_RADAR, SUM(POSITIVES_RADAR) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_WEEK) AS POSITIVES_RADAR_ACC,
	   CASE WHEN CONFIRMED_POSITIVES = 0 THEN 0.00 ELSE ((POSITIVES_RADAR * 100.0) / CONFIRMED_POSITIVES) END AS POSITIVES_RADAR_RATIO,
	   CASE WHEN (SUM(CONFIRMED_POSITIVES) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_WEEK)) = 0 THEN 0.00 ELSE ((SUM(POSITIVES_RADAR) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_WEEK)) * 100.0/ (SUM(CONFIRMED_POSITIVES) OVER (PARTITION BY CCAA_ID ORDER BY YEAR_WEEK))) END AS POSITIVES_RADAR_ACC_RATIO
FROM (
SELECT DATE_PART('YEAR', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE))::TEXT AS YEAR,
	   LPAD(DATE_PART('WEEK', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE))::TEXT, 2, '0') AS WEEK,
	   CONCAT(DATE_PART('YEAR', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE))::TEXT, LPAD(DATE_PART('WEEK', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE))::TEXT, 2, '0'))::INT AS YEAR_WEEK,
	   C.DE_CCAA_ID AS CCAA_ID,
	   C.DE_CCAA_NAME AS CCAA_NAME,
	   SUM(NM_POSITIVES_CONFIRMED) AS CONFIRMED_POSITIVES,
	   COUNT(*) - COUNT(NM_POSITIVES_CONFIRMED) AS CHECK_POSITIVES_CONFIRMED,
	   SUM(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS DELIVERED_CODES_POSITIVE_CONFIRMED,
	   COUNT(*) - COUNT(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED,
	   SUM(NM_POSITIVES_RADAR) AS POSITIVES_RADAR,
	   COUNT(*) - COUNT(NM_POSITIVES_RADAR) AS CHECK_POSITIVES_RADAR
FROM KPI.STATISTICS_RADAR_CCAA S
INNER JOIN KPI.CCAA C ON S.DE_CCAA_ID = C.DE_CCAA_ID
WHERE S.FC_STATISTICS_DATE >= C.FC_START_DATE
GROUP BY YEAR, WEEK, CCAA_ID
ORDER BY YEAR, WEEK, CCAA_ID ) T
WHERE T.YEAR_WEEK < CONCAT(DATE_PART('YEAR', DATE_TRUNC('WEEK', NOW()))::TEXT, LPAD(DATE_PART('WEEK', DATE_TRUNC('WEEK', NOW()))::TEXT, 2, '0'))::INT
  AND T.CHECK_POSITIVES_CONFIRMED = 0 
  AND T.CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED = 0
  AND T.CHECK_POSITIVES_RADAR = 0
ORDER BY YEAR_WEEK, CCAA_ID;


CREATE OR REPLACE VIEW KPI.VIEW_DATA_TOTAL_MONTH_STATISTICS AS
SELECT YEAR, MONTH, YEAR_MONTH,
	  CONFIRMED_POSITIVES,
     SUM(CONFIRMED_POSITIVES) OVER (ORDER BY YEAR_MONTH) AS CONFIRMED_POSITIVES_ACC,
     DELIVERED_CODES_POSITIVE_CONFIRMED, 
	   SUM(DELIVERED_CODES_POSITIVE_CONFIRMED) OVER (ORDER BY YEAR_MONTH) AS DELIVERED_CODES_POSITIVE_CONFIRMED_ACC,
	   CASE WHEN CONFIRMED_POSITIVES = 0 THEN 0.00 ELSE ((DELIVERED_CODES_POSITIVE_CONFIRMED * 100.0) / CONFIRMED_POSITIVES) END AS DELIVERED_CODES_POSITIVE_CONFIRMED_RATIO,
	   CASE WHEN (SUM(CONFIRMED_POSITIVES) OVER (ORDER BY YEAR_MONTH)) = 0 THEN 0.00 ELSE (((SUM(DELIVERED_CODES_POSITIVE_CONFIRMED) OVER (ORDER BY YEAR_MONTH)) * 100.0) / (SUM(CONFIRMED_POSITIVES) OVER (ORDER BY YEAR_MONTH))) END AS DELIVERED_CODES_POSITIVE_CONFIRMED_ACC_RATIO,
	   POSITIVES_RADAR, SUM(POSITIVES_RADAR) OVER (ORDER BY YEAR_MONTH) AS POSITIVES_RADAR_ACC,
	   CASE WHEN CONFIRMED_POSITIVES = 0 THEN 0.00 ELSE ((POSITIVES_RADAR * 100.0) / CONFIRMED_POSITIVES) END AS POSITIVES_RADAR_RATIO,
	   CASE WHEN (SUM(CONFIRMED_POSITIVES) OVER (ORDER BY YEAR_MONTH)) = 0 THEN 0.00 ELSE ((SUM(POSITIVES_RADAR) OVER (ORDER BY YEAR_MONTH)) * 100.0/ (SUM(CONFIRMED_POSITIVES) OVER (ORDER BY YEAR_MONTH))) END AS POSITIVES_RADAR_ACC_RATIO
FROM (
SELECT DATE_PART('YEAR', FC_STATISTICS_DATE::DATE) AS YEAR,
	   LPAD(DATE_PART('MONTH', FC_STATISTICS_DATE::DATE)::TEXT, 2, '0') AS MONTH,
	   CONCAT(DATE_PART('YEAR', FC_STATISTICS_DATE::DATE), LPAD(DATE_PART('MONTH', FC_STATISTICS_DATE::DATE)::TEXT, 2, '0'))::INT AS YEAR_MONTH,
	   SUM(NM_POSITIVES_CONFIRMED) AS CONFIRMED_POSITIVES,
	   COUNT(*) - COUNT(NM_POSITIVES_CONFIRMED) AS CHECK_POSITIVES_CONFIRMED,
	   SUM(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS DELIVERED_CODES_POSITIVE_CONFIRMED,
	   COUNT(*) - COUNT(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED,
	   SUM(NM_POSITIVES_RADAR) AS POSITIVES_RADAR,
	   COUNT(*) - COUNT(NM_POSITIVES_RADAR) AS CHECK_POSITIVES_RADAR
FROM KPI.STATISTICS_RADAR_CCAA S
INNER JOIN KPI.CCAA C ON S.DE_CCAA_ID = C.DE_CCAA_ID
WHERE S.FC_STATISTICS_DATE >= C.FC_START_DATE
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH) T
WHERE T.YEAR_MONTH < CONCAT(DATE_PART('YEAR', NOW())::TEXT, LPAD(DATE_PART('MONTH', NOW())::TEXT, 2, '0'))::INT
  AND T.CHECK_POSITIVES_CONFIRMED = 0 
  AND T.CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED = 0
  AND T.CHECK_POSITIVES_RADAR = 0
ORDER BY YEAR_MONTH;


CREATE OR REPLACE VIEW KPI.VIEW_DATA_TOTAL_WEEK_STATISTICS AS
SELECT YEAR, WEEK, YEAR_WEEK, 
 	   CONFIRMED_POSITIVES,
       SUM(CONFIRMED_POSITIVES) OVER (ORDER BY YEAR_WEEK) AS CONFIRMED_POSITIVES_ACC,
       DELIVERED_CODES_POSITIVE_CONFIRMED, 
	   SUM(DELIVERED_CODES_POSITIVE_CONFIRMED) OVER (ORDER BY YEAR_WEEK) AS DELIVERED_CODES_POSITIVE_CONFIRMED_ACC,
	   CASE WHEN CONFIRMED_POSITIVES = 0 THEN 0.00 ELSE ((DELIVERED_CODES_POSITIVE_CONFIRMED * 100.0) / CONFIRMED_POSITIVES) END AS DELIVERED_CODES_POSITIVE_CONFIRMED_RATIO,
	   CASE WHEN (SUM(CONFIRMED_POSITIVES) OVER (ORDER BY YEAR_WEEK)) = 0 THEN 0.00 ELSE (((SUM(DELIVERED_CODES_POSITIVE_CONFIRMED) OVER (ORDER BY YEAR_WEEK)) * 100.0) / (SUM(CONFIRMED_POSITIVES) OVER (ORDER BY YEAR_WEEK))) END AS DELIVERED_CODES_POSITIVE_CONFIRMED_ACC_RATIO,
	   POSITIVES_RADAR, SUM(POSITIVES_RADAR) OVER (ORDER BY YEAR_WEEK) AS POSITIVES_RADAR_ACC,
	   CASE WHEN CONFIRMED_POSITIVES = 0 THEN 0.00 ELSE ((POSITIVES_RADAR * 100.0) / CONFIRMED_POSITIVES) END AS POSITIVES_RADAR_RATIO,
	   CASE WHEN (SUM(CONFIRMED_POSITIVES) OVER (ORDER BY YEAR_WEEK)) = 0 THEN 0.00 ELSE ((SUM(POSITIVES_RADAR) OVER (ORDER BY YEAR_WEEK)) * 100.0/ (SUM(CONFIRMED_POSITIVES) OVER (ORDER BY YEAR_WEEK))) END AS POSITIVES_RADAR_ACC_RATIO
FROM (
SELECT DATE_PART('YEAR', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE))::TEXT AS YEAR,
	   LPAD(DATE_PART('WEEK', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE))::TEXT, 2, '0') AS WEEK,
	   CONCAT(DATE_PART('YEAR', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE))::TEXT, LPAD(DATE_PART('WEEK', DATE_TRUNC('WEEK', FC_STATISTICS_DATE::DATE))::TEXT, 2, '0'))::INT AS YEAR_WEEK,
	   SUM(NM_POSITIVES_CONFIRMED) AS CONFIRMED_POSITIVES,
	   COUNT(*) - COUNT(NM_POSITIVES_CONFIRMED) AS CHECK_POSITIVES_CONFIRMED,
	   SUM(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS DELIVERED_CODES_POSITIVE_CONFIRMED,
	   COUNT(*) - COUNT(NM_DELIVERED_CODES_POSITIVE_CONFIRMED) AS CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED,
	   SUM(NM_POSITIVES_RADAR) AS POSITIVES_RADAR,
	   COUNT(*) - COUNT(NM_POSITIVES_RADAR) AS CHECK_POSITIVES_RADAR
FROM KPI.STATISTICS_RADAR_CCAA S
INNER JOIN KPI.CCAA C ON S.DE_CCAA_ID = C.DE_CCAA_ID
WHERE S.FC_STATISTICS_DATE >= C.FC_START_DATE
GROUP BY YEAR, WEEK
ORDER BY YEAR, WEEK ) T
WHERE T.YEAR_WEEK < CONCAT(DATE_PART('YEAR', DATE_TRUNC('WEEK', NOW()))::TEXT, LPAD(DATE_PART('WEEK', DATE_TRUNC('WEEK', NOW()))::TEXT, 2, '0'))::INT
  AND T.CHECK_POSITIVES_CONFIRMED = 0 
  AND T.CHECK_DELIVERED_CODES_POSITIVE_CONFIRMED = 0
  AND T.CHECK_POSITIVES_RADAR = 0
ORDER BY YEAR_WEEK;
